### ISSUE TITLE
pip install Impossible, Probleem with the package

### ISSUE THREAD

**Issue by flosrv** [uhh-lt/amharicprocessor#5]
C:\Users\flosr\Engineering\Data Engineering>pip install amseg
Collecting amseg
  Downloading amseg-2.3.tar.gz (11 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\flosr\AppData\Local\Temp\pip-install-_4vble62\amseg_2274f9ad75f64023889cc7957e9016b5\setup.py", line 11, in <module>
          long_description=readme(),
                           ^^^^^^^^
        File "C:\Users\flosr\AppData\Local\Temp\pip-install-_4vble62\amseg_2274f9ad75f64023889cc7957e9016b5\setup.py", line 4, in readme
          return f.read()
                 ^^^^^^^^
        File "C:\Users\flosr\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 778: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Khayo-7** [comment]
Source of error: Unable to decode the content of the README.rst file

Temporary Solution: 

1. Remove the content of the README.rst file 
or 
2. Comment out the call to the `readme()` function in the setup function call in the `setup.py` file as
```
setup(
  ...
  # long_description=readme(),
...
)
```

Fast Solution: Removing the content of README.rst

1. Clone the git repo for `amseg` library
```
git clone https://github.com/uhh-lt/amharicprocessor.git
```
```
cd amharicprocessor
```

2. Remove the content of the README.rst file, which was raising the above error
```
echo. > README.rst
```

3. Install the package
```
python setup.py install
```

4. Clean the downloaded files
```
cd ..
```
```
rmdir /s /q amharicprocessor
```

Verify installation with
```
pip install amseg
```
